export var DETAILS_WINDOW_UUID = 'MPH_POC_PF_API_VIEWS';
export var DETAILS_WINDOW_TOPIC = 'MPH_STOCK_DETAILS_POC_TOPIC';
export var DETAILS_WINDOW_TOPIC_IND = 'MPH_STOCK_DETAILS_POC_TOPIC_IND';
export var STOCKSLIST_WINDOW_UUID = 'MPH_POC_STOCKLIST_PF_API_VIEWS';
export var TOPIC__DROPDOWN = 'TOPIC__DROPDOWN';
export var TOPIC__SYMBOL_CHANGE = 'TOPIC__SYMBOL_CHANGE'

// From HTML To Java
export var JAVA_NATIVE_UUID = 'JAVA_NATIVE_UUID';
export var JAVA_NATIVE_TOPIC = 'JAVA_NATIVE_TOPIC';

// From Java To HTML
export var JAVA_NATIVE_TO_HTML_UUID = 'OpenFinUIAppDemo';
export var JAVA_NATIVE_TO_HTML_TOPIC = 'strawmanScreenData1';
export var JAVA_NATIVE_TO_HTML_TOPIC__CHART = 'JAVA_NATIVE_TO_HTML_TOPIC__CHART';
export var JAVA_NATIVE_TO_HTML_TOPIC__DETAILS = 'JAVA_NATIVE_TO_HTML_TOPIC__DETAILS';
export var JAVA_NATIVE_TO_HTML_TOPIC__FOREX = 'JAVA_NATIVE_TO_HTML_TOPIC__FOREX';

export var WILDCARD_UUID = '*';

export var ENTRYPOINT = 'HTML'

export var SHOW_ADD_SYMBOL = true;
export var SHOW_ADD_GROUP = false;
export var SHOW_SELL_SHORT = true;