export var DETAILS_WINDOW_UUID = 'MPH_POC_PF_API_VIEWS';
export var DETAILS_WINDOW_TOPIC = 'MPH_STOCK_DETAILS_POC_TOPIC';
export var DETAILS_WINDOW_TOPIC_IND = 'MPH_STOCK_DETAILS_POC_TOPIC_IND';
export var STOCKSLIST_WINDOW_UUID = 'MPH_POC_STOCKLIST_PF_API_VIEWS';

// From HTML To Java
export var JAVA_NATIVE_UUID = 'JAVA_NATIVE_UUID';
export var JAVA_NATIVE_TOPIC = 'JAVA_NATIVE_TOPIC';

// From Java To HTML
export var JAVA_NATIVE_TO_HTML_UUID = 'OpenFinUIAppDemo';
export var JAVA_NATIVE_TO_HTML_TOPIC = 'strawmanScreenData1';